[package]
name = "catr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.16"
rand = "0.8.5"

[dev-dependencies]
assert_cmd = "1"
predicates = "1"
